apiVersion: v1
kind: Service
metadata:
  name: realworld-backend-service
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
  selector:
    stack: backend
  type: LoadBalancer