version: '3.6'

services:

    server:
        container_name: realworld-backend
        build:
            context: ./Conduit_NodeJS
        ports:
            - "8080:8080"
        volumes:
            - ./Conduit_NodeJS:/server
            - /server/node_modules
        depends_on:
            - postgres
        networks:
            - realworld-red

    client:
        container_name: realworld-frontend
        build:
            context: ./vue3-realworld-example-app
            target: production-stage
        ports:
            - "80:3000"
        volumes:
            - ./vue3-realworld-example-app:/client
            - /client/node_modules
        depends_on:
            - server
        networks:
            - realworld-red

    postgres:
        container_name: postgres
        image: postgres:13-alpine
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - realworld-red

networks:
    realworld-red:

volumes:
    pgdata: