apiVersion: v1
kind: Service
metadata:
  name: realworld-frontend-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 3000
  selector:
    stack: frontend
  type: LoadBalancer