version: '3.6'

services:

    server:
        container_name: realworld-backend
        build:
            context: ./Conduit_NodeJS
        ports:
            - "8080:8080"
        volumes:
            - ./Conduit_NodeJS:/server
            - /server/node_modules
        depends_on:
            - mariadb
        networks:
            - realworld-red

    client:
        container_name: realworld-frontend
        build:
            context: ./vue3-realworld-example-app
            target: development-stage
        ports:
            - "3000:3000"
        volumes:
            - ./vue3-realworld-example-app:/client
            - /client/node_modules
        depends_on:
            - server
        networks:
            - realworld-red

    mariadb:
        container_name: mariadb
        image: mariadb:10.6.1
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - ./.env
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - realworld-red

networks:
    realworld-red:

volumes:
    dbdata: