apiVersion: v1
kind: Secret
metadata:
  namespace: realworld
  name: backend-secret
type: Opaque
stringData:
  DB_HOST:    mariadb-service
  DB_PORT:    "3306"
  DB_USER:    root
  DB_PASS:    mysecretpassword
  DB_NAME:    realworld_db