apiVersion: v1
kind: Service
metadata:
  namespace: realworld
  name: backend-service
spec:
  ports:
    - name: http-backend
      port: 8080
      targetPort: 8080
  selector:
    stack: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: realworld
  name: backend-deployment
spec:
  selector:
    matchLabels:
      stack: backend
  replicas: 3
  template:
    metadata:
      labels:
        stack: backend
    spec:
      containers:
        - name: backend-container
          image: realworld-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_NAME