apiVersion: v1
kind: Service
metadata:
  namespace: realworld
  name: mariadb-service
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    stack: database
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: realworld
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: realworld
  name: mariadb-deployment
spec:
  selector:
    matchLabels:
      stack: database
  replicas: 1
  # Pod Template
  template:
    metadata:
      labels:
        stack: database
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:10.6.1
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysecretpassword
        - name: MYSQL_DATABASE
          value: realworld_db
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
