apiVersion: v1
kind: Service
metadata:
  name: realworld-frontend-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 3000
  selector:
    stack: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      stack: frontend
  replicas: 3
  template:
    metadata:
      labels:
        stack: frontend
    spec:
      containers:
        - name: frontend-container
          image: us.gcr.io/[ID_DEL_PROYECTO]/realworld-frontend
          ports:
            - containerPort: 3000
              protocol: TCP